### ISSUE TITLE
Shouldn't it be readwrite?

### ISSUE THREAD

**Issue by zdrossman** [learn-co-curriculum/captain-morgans-notifications#3]
Check it out. I changed it in solution, but should be true in master. 

https://github.com/flatiron-school-curriculum/captain-morgans-notifications/blob/master/OpenMe/FISPiratesDataStore.h#L14

**Comment by AnnJohn** [comment]
Iceboxing the issue for now

**Comment by markedwardmurray** [comment]
Readonly is correct. Reversed the change on the `solution` branch.
